name = "vikrant-portfolio-visitor-counter"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespace binding for visitor count storage
[[kv_namespaces]]
binding = "VISITOR_COUNT"
id = "YOUR_KV_NAMESPACE_ID_HERE"

# Routes - update with your actual domain
# routes = [
#   { pattern = "yourdomain.com/api/*", zone_name = "yourdomain.com" }
# ]
